
const DEFAULT_WEEKDAY_LABELS = [
    "Mo",
    "Tu",
    "We",
    "Th",
    "Fr",
    "Sa",
    "Su"
];
const DEFAULT_CELL_HEIGHT = 16;
const DEFAULT_CELL_WIDTH = 64;
const DEFAULT_HOURS_PER_CELL = 0.5;
const DEFAULT_CELLS_PER_TIME_LABEL = 4;

export {
    DEFAULT_WEEKDAY_LABELS,
    DEFAULT_CELL_HEIGHT,
    DEFAULT_CELL_WIDTH,
    DEFAULT_HOURS_PER_CELL,
    DEFAULT_CELLS_PER_TIME_LABEL
};
